import { Injectable, Logger } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';
import { McqTest } from '../mcq/schemas/mcq-test.schema';

export interface LongQuestion {
    text: string;
    marks: number;
}

/**
 * PdfGeneratorService
 *
 * Wraps pdfkit to generate well-typed, printable exam sheets synchronously
 * streaming memory directly to a Buffer array.
 */
@Injectable()
export class PdfGeneratorService {
    private readonly logger = new Logger(PdfGeneratorService.name);

    /**
     * Generates a printable MCQ Question Paper. (No answers shown).
     */
    async generateMcqTestPdf(test: McqTest): Promise<Buffer> {
        this.logger.log(`Generating MCQ Question Paper PDF for Test: ${test._id}`);
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers: Buffer[] = [];

        return new Promise((resolve, reject) => {
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', reject);

            const letters = ['A', 'B', 'C', 'D'];

            // Title Header
            doc.fontSize(20).font('Helvetica-Bold').text(test.title || 'MCQ Test', { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica').text(`Generated by Willofire | Total Questions: ${test.totalQuestions}`, { align: 'center' });
            doc.moveDown(2);

            // Questions loop
            test.questions.forEach((q, index) => {
                doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${q.question}`);
                doc.moveDown(0.5);

                doc.fontSize(11).font('Helvetica');
                q.options.forEach((opt, optIndex) => {
                    const letter = letters[optIndex] || '?';
                    doc.text(`    ${letter}) ${opt}`);
                });

                doc.moveDown(1.5);
            });

            doc.end();
        });
    }

    /**
     * Generates a printable MCQ Answer Key (Highlights correct answers and prints explanations).
     */
    async generateMcqAnswerKeyPdf(test: McqTest): Promise<Buffer> {
        this.logger.log(`Generating MCQ Answer Key PDF for Test: ${test._id}`);
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers: Buffer[] = [];

        return new Promise((resolve, reject) => {
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', reject);

            const letters = ['A', 'B', 'C', 'D'];

            // Answer Key Header
            doc.fontSize(20).font('Helvetica-Bold').text(`Answer Key: ${test.title || 'MCQ Test'}`, { align: 'center' });
            doc.moveDown(2);

            // Questions loop
            test.questions.forEach((q, index) => {
                doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${q.question}`);
                doc.moveDown(0.5);

                const correctLetter = letters[q.correctAnswer] || '?';
                const correctText = q.options[q.correctAnswer] || 'Unknown';

                doc.fontSize(11).font('Helvetica-Bold').fillColor('green').text(`    Answer: ${correctLetter}) ${correctText}`);
                doc.moveDown(0.5);

                doc.fontSize(10).font('Helvetica-Oblique').fillColor('black').text(`    Explanation: ${q.explanation}`);
                doc.moveDown(1.5);
            });

            doc.end();
        });
    }

    /**
     * Generates an array of AI Long Questions with marked writing spacers natively.
     */
    async generateLongQuestionPdf(title: string, questions: LongQuestion[]): Promise<Buffer> {
        this.logger.log(`Generating Long Question PDF: ${title}`);
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers: Buffer[] = [];

        return new Promise((resolve, reject) => {
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', reject);

            doc.fontSize(20).font('Helvetica-Bold').text(title, { align: 'center' });
            doc.moveDown(2);

            questions.forEach((q, index) => {
                doc.fontSize(14).font('Helvetica-Bold').text(`Q${index + 1}. ${q.text}`);
                doc.moveDown(0.2);
                doc.fontSize(10).font('Helvetica-Oblique').text(`(${q.marks} marks)`, { align: 'right' });

                // Add writing space (a simple separator line pattern)
                doc.moveDown(2);
                for (let i = 0; i < 5; i++) {
                    doc.fontSize(12).fillColor('#cccccc').text('________________________________________________________________________________', { align: 'center' });
                    doc.moveDown(1.5);
                }

                doc.fillColor('black').moveDown(2);
            });

            doc.end();
        });
    }
}
